spring.datasource.url=jdbc:postgresql://localhost:5434/labAcc
spring.datasource.username=lab
spring.datasource.password=lab

spring.jpa.hibernate.ddl-auto=validate

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
