-- Countries
INSERT INTO countries (name, continent)
VALUES ('Germany', 'Europe'),
       ('France', 'Europe'),
       ('Italy', 'Europe'),
       ('Spain', 'Europe'),
       ('United States', 'North America'),
       ('Canada', 'North America'),
       ('Japan', 'Asia'),
       ('China', 'Asia'),
       ('Brazil', 'South America'),
       ('Australia', 'Australia'),
       ('South Korea', 'Asia'),
       ('Mexico', 'North America'),
       ('Greece', 'Europe'),
       ('Egypt', 'Africa'),
       ('South Africa', 'Africa'),
       ('Argentina', 'South America'),
       ('Netherlands', 'Europe'),
       ('Thailand', 'Asia'),
       ('New Zealand', 'Australia'),
       ('Portugal', 'Europe'),
       ('Norway', 'Europe'),
       ('India', 'Asia'),
       ('Switzerland', 'Europe'),
       ('Vietnam', 'Asia'),
       ('Peru', 'South America'),
       ('Ireland', 'Europe'),
       ('Kenya', 'Africa'),
       ('Turkey', 'Asia'),
       ('Austria', 'Europe'),
       ('Singapore', 'Asia');

-- Hosts
INSERT INTO hosts (name, surname, country_id, created_at, updated_at)
VALUES ('John', 'Smith', 1, NOW(), NOW()),
       ('Marie', 'Dubois', 2, NOW(), NOW()),
       ('Luca', 'Bianchi', 3, NOW(), NOW()),
       ('Carlos', 'Garcia', 4, NOW(), NOW()),
       ('James', 'Johnson', 5, NOW(), NOW()),
       ('Emma', 'Wilson', 6, NOW(), NOW()),
       ('Kenji', 'Tanaka', 7, NOW(), NOW()),
       ('Wei', 'Zhang', 8, NOW(), NOW()),
       ('Pedro', 'Silva', 9, NOW(), NOW()),
       ('Oliver', 'Brown', 10, NOW(), NOW()),
       ('Min-su', 'Kim', 11, NOW(), NOW()),
       ('Elena', 'Rodriguez', 12, NOW(), NOW()),
       ('Nikos', 'Papadopoulos', 13, NOW(), NOW()),
       ('Amira', 'Mansour', 14, NOW(), NOW()),
       ('Thabo', 'Mbeki', 15, NOW(), NOW()),
       ('Sofia', 'Martinez', 16, NOW(), NOW()),
       ('Lars', 'De Jong', 17, NOW(), NOW()),
       ('Somchai', 'Sato', 18, NOW(), NOW()),
       ('Liam', 'Williams', 19, NOW(), NOW()),
       ('Beatriz', 'Ferreira', 20, NOW(), NOW()),
       ('Ingrid', 'Larsen', 21, NOW(), NOW()),
       ('Arjun', 'Patel', 22, NOW(), NOW()),
       ('Heidi', 'Müller', 23, NOW(), NOW()),
       ('Linh', 'Nguyen', 24, NOW(), NOW()),
       ('Mateo', 'Quispe', 25, NOW(), NOW()),
       ('Siobhan', 'O’Connor', 26, NOW(), NOW()),
       ('Zuri', 'Kamau', 27, NOW(), NOW()),
       ('Emre', 'Yilmaz', 28, NOW(), NOW()),
       ('Franz', 'Wagner', 29, NOW(), NOW()),
       ('Zhi', 'Tan', 30, NOW(), NOW());

-- Accommodations
INSERT INTO accomodations (name, category, host_id, state, num_rooms, created_at, updated_at)
VALUES ('Berlin Central Room', 'ROOM', 1, 'GOOD', 5, NOW(), NOW()),
       ('Paris Luxury House', 'HOUSE', 2, 'GOOD', 8, NOW(), NOW()),
       ('Rome Modern Flat', 'FLAT', 3, 'GOOD', 4, NOW(), NOW()),
       ('Madrid City Apartment', 'APARTMENT', 4, 'BAD', 6, NOW(), NOW()),
       ('New York Grand Hotel', 'HOTEL', 5, 'GOOD', 40, NOW(), NOW()),
       ('Toronto Comfort Motel', 'MOTEL', 6, 'GOOD', 20, NOW(), NOW()),
       ('Tokyo Small Room', 'ROOM', 7, 'BAD', 3, NOW(), NOW()),
       ('Shanghai Business Hotel', 'HOTEL', 8, 'GOOD', 35, NOW(), NOW()),
       ('Rio Beach House', 'HOUSE', 9, 'GOOD', 7, NOW(), NOW()),
       ('Sydney Harbor Apartment', 'APARTMENT', 10, 'BAD', 5, NOW(), NOW()),
       ('Seoul Skyline Studio', 'APARTMENT', 11, 'GOOD', 2, NOW(), NOW()),
       ('Cancun Beachfront Villa', 'HOUSE', 12, 'GOOD', 10, NOW(), NOW()),
       ('Santorini White House', 'HOUSE', 13, 'GOOD', 4, NOW(), NOW()),
       ('Cairo Nile View Room', 'ROOM', 14, 'BAD', 2, NOW(), NOW()),
       ('Cape Town Safari Lodge', 'HOTEL', 15, 'GOOD', 15, NOW(), NOW()),
       ('Buenos Aires Tango Loft', 'FLAT', 16, 'GOOD', 3, NOW(), NOW()),
       ('Amsterdam Canal Studio', 'FLAT', 17, 'GOOD', 2, NOW(), NOW()),
       ('Bangkok Riverside Inn', 'MOTEL', 18, 'BAD', 12, NOW(), NOW()),
       ('Auckland Mountain Retreat', 'HOUSE', 19, 'GOOD', 6, NOW(), NOW()),
       ('Lisbon Old Town Suite', 'ROOM', 20, 'GOOD', 1, NOW(), NOW()),
       ('Oslo Fjord Cabin', 'HOUSE', 21, 'GOOD', 3, NOW(), NOW()),
       ('Mumbai Heritage Suite', 'ROOM', 22, 'GOOD', 1, NOW(), NOW()),
       ('Alpine Chalet Zermatt', 'HOUSE', 23, 'GOOD', 12, NOW(), NOW()),
       ('Hanoi Old Quarter Inn', 'HOTEL', 24, 'BAD', 25, NOW(), NOW()),
       ('Cusco Mountain Lodge', 'MOTEL', 25, 'GOOD', 8, NOW(), NOW()),
       ('Dublin City Penthouse', 'APARTMENT', 26, 'GOOD', 4, NOW(), NOW()),
       ('Nairobi Savannah Villa', 'HOUSE', 27, 'GOOD', 10, NOW(), NOW()),
       ('Istanbul Bosphorus View', 'FLAT', 28, 'BAD', 3, NOW(), NOW()),
       ('Vienna Opera Studio', 'ROOM', 29, 'GOOD', 1, NOW(), NOW()),
       ('Marina Bay Luxury Suite', 'HOTEL', 30, 'GOOD', 50, NOW(), NOW());
